= メモ書き

== AsciiDoc Template

----
= Title
:toc: left
:sectnums:
:imagesdir: images
:webfonts!:

== Sec1

== Sec2

----

== macOS スクショ

=== 「スクリーンショット YYYY-MM-DD hh.mm.ss」の「スクリーンショット」を指定の文字列に変更

`defaults write com.apple.screencapture name ファイル名`

=== 部分スクリーンショットでの陰影をなくす

`defaults write com.apple.screencapture disable-shadow -bool true`

== macOS で SMB ブラウジングの動作を調整する

https://support.apple.com/ja-jp/HT208209

SMB のファイルブラウジングを高速化するには、macOS が SMB 共有上の「.DS_Store」ファイルを読み取らないように阻止できます。 +
そうすれば、Finder で基本情報だけを使って、各フォルダの中身がすぐにアルファベット順で表示されるようになります。 +
以下のターミナルコマンドを使います。

`defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE`

その後、macOS アカウントからログアウトし、ログインし直してください。

並べ替えを再び有効にするには、以下のコマンドを使います。

`defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool FALSE`

== Nortonの脆弱性保護が更新されない

アクティビティモニターで``SymDaemon``を終了させると更新されるっぽい。

== 単語

* ブルーム
* リムライト
* 極座標
* トゥーンレンダリング
* アウトラインレンダリング
* フォグ
* ブラー
* パーリンノイズ
* ディゾルブ（シェーダ）
* ディストーション（シェーダ）
* テクスチャアニメーション
* ライトベイク？
* テッセレーション

== PostgreSQL

[source, sh]
----
$ mkdir postgres

$ initdb ./postgres -E utf8

$ vim postgres/postgresql.conf
listen_addresses = 'localhost'

$ postgres -D ./postgres

$ psql -d postgres
----
