= Unity Coding Conventions

== File format

* インデント -> 2 space
* 文字コード -> UTF-8
* 改行コード -> LF

== Class layout

[source, cs]
----
// Copyright information
// Using directives

namespace CompanyName.Technology.Feature
{
    // Global Delegates

    class ClassName
    {
        // 1. Fields, Constants
        // 2. Constructors
        // 3. Events
        // 4. Properties
        // 5. Methods
        // 6. Nested Types
    }
}
----

== Naming rules

[cols="30,20,50a", options="header"]
|===
|識別子
|大文字小文字の区別
|例

|名前空間
|Pascal
|
``namespace System.Security { ... }``

|型
|Pascal
|
``public class StreamReader { ... }``

|インターフェース
|I + Pascal
|
``public interface IEnumerable { ... }``

|メソッド
|Pascal
|
``public class Object {`` +
&emsp;``public virtual string ToString();`` +
``}``

|プロパティ
|Pascal
|
``public class String {`` +
&emsp;``public int Length { get; }`` +
``}``

|イベント
|Pascal
|
``public class Process {`` +
&emsp;``public event EventHandler Exited;`` +
``}``

|定数
|Pascal
|
``public class MessageQueue {`` +
&emsp;``public static readonly TimeSpan InfiniteTimeout;`` +
``}`` +
``public struct UInt32 {`` +
&emsp;``public const uint Min = 0;`` +
``}``

|プライベートフィールド
|_ + Camel
|
``public class Player {`` +
&emsp;``private int _atkPower;`` +
``}``

|列挙値
|Pascal
|
``public enum FileMode {`` +
&emsp;``Append,`` +
&emsp;``...`` +
``}``

|パラメーター
|Camel
|
``public class Convert {`` +
&emsp;``public static int ToInt32(string valueStr);`` +
``}``
|===

== Performances

=== 空のイベントメソッドは消す

イベントメソッド? => `Awake()` や `Start()` などの Unity から呼び出されるメソッド

呼び出しにコストがかかるので必要ない場合は削除する。
